// import './globals.css'
import '../public/css/all.min.css'
import '../public/css/animate.css'
import '../public/css/bootstrap.min.css'
import '../public/css/nice-select.css'
import '../public/css/responsive.css'
import '../public/css/slick.css'
import '../public/css/spacing.css'
import '../public/css/style.css'
import '../public/css/style2.css'
import '../public/css/responsive2.css'
import '../public/css/venobox.min.css'
import { Inter } from 'next/font/google'
import Topbar from './components/Topbar'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kansha Express Hibachi & Sushi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
